"""
Data loading utilities for exploratory analysis.

This module provides a consistent interface for loading the
power-grid datasets generated by Milestone 1.

The loader does not modify, normalize, or otherwise transform
the data. EDA should begin from the processed datasets while
preserving the original physical units.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import pandas as pd


@dataclass
class EDADataset:
    """
    Container for the datasets used during EDA.
    """

    bus: pd.DataFrame
    line: pd.DataFrame

    @property
    def bus_rows(self) -> int:
        return len(self.bus)

    @property
    def line_rows(self) -> int:
        return len(self.line)

    @property
    def bus_columns(self) -> list[str]:
        return list(self.bus.columns)

    @property
    def line_columns(self) -> list[str]:
        return list(self.line.columns)


class EDADataLoader:
    """
    Load datasets produced by the data-engineering pipeline.

    Parameters
    ----------
    processed_root:
        Directory containing processed datasets.

    simulated_root:
        Directory containing raw simulation measurements.
    """

    def __init__(
        self,
        processed_root: str | Path = "data/processed",
        simulated_root: str | Path = "data/simulated",
    ) -> None:

        self.processed_root = Path(
            processed_root
        )

        self.simulated_root = Path(
            simulated_root
        )

                                                                        
                        
                                                                        

    def load_bus_data(
        self,
        normalized: bool = False,
    ) -> pd.DataFrame:
        """
        Load processed bus measurements.

        Parameters
        ----------
        normalized:
            If True, load the train-normalized dataset.
            If False, load the physically meaningful processed data.

        Returns
        -------
        pandas.DataFrame
        """

        if normalized:

            path = (
                self.processed_root
                / "normalized"
                / "train.csv"
            )

        else:

            path = (
                self.processed_root
                / "bus_measurements_processed.csv"
            )

        return self._read_csv(
            path
        )

                                                                        
                  
                                                                        

    def load_raw_bus_data(
        self,
    ) -> pd.DataFrame:
        """
        Load raw simulated bus measurements.
        """

        path = (
            self.simulated_root
            / "measurements"
            / "bus_measurements.csv"
        )

        return self._read_csv(
            path
        )

                                                                        
               
                                                                        

    def load_line_data(
        self,
    ) -> pd.DataFrame:
        """
        Load raw simulated line measurements.
        """

        path = (
            self.simulated_root
            / "measurements"
            / "line_measurements.csv"
        )

        return self._read_csv(
            path
        )

                                                                        
                               
                                                                        

    def load_split(
        self,
        split: str,
        normalized: bool = False,
    ) -> pd.DataFrame:
        """
        Load one dataset split.

        Parameters
        ----------
        split:
            "train", "validation", or "test".

        normalized:
            Whether to load normalized data.
        """

        valid_splits = {
            "train",
            "validation",
            "test",
        }

        if split not in valid_splits:

            raise ValueError(
                f"Invalid split '{split}'. "
                f"Choose from {sorted(valid_splits)}."
            )

        if normalized:

            path = (
                self.processed_root
                / "normalized"
                / f"{split}.csv"
            )

        else:

            path = (
                self.processed_root
                / f"{split}.csv"
            )

        return self._read_csv(
            path
        )

                                                                        
                          
                                                                        

    def load_all(
        self,
    ) -> EDADataset:
        """
        Load the primary bus and line datasets used for EDA.
        """

        bus = self.load_bus_data(
            normalized=False
        )

        line = self.load_line_data()

        return EDADataset(
            bus=bus,
            line=line,
        )

                                                                        
                        
                                                                        

    @staticmethod
    def _read_csv(
        path: Path,
    ) -> pd.DataFrame:
        """
        Read a CSV while preserving timestamps.
        """

        if not path.exists():

            raise FileNotFoundError(
                f"Dataset not found: {path}"
            )

        dataframe = pd.read_csv(
            path,
            parse_dates=["timestamp"],
        )

        if dataframe.empty:

            raise ValueError(
                f"Dataset is empty: {path}"
            )

        return dataframe

                                                                        
                     
                                                                        

    def summary(
        self,
        dataframe: pd.DataFrame,
        name: str = "dataset",
    ) -> None:
        """
        Print a concise dataset summary.
        """

        print()
        print("=" * 70)
        print(
            f"EDA DATASET SUMMARY: {name}"
        )
        print("=" * 70)

        print(
            f"Rows       : {len(dataframe)}"
        )

        print(
            f"Columns    : {len(dataframe.columns)}"
        )

        print(
            f"Time start : "
            f"{dataframe['timestamp'].min()}"
        )

        print(
            f"Time end   : "
            f"{dataframe['timestamp'].max()}"
        )

        print(
            f"Unique buses/lines: "
            f"{dataframe.iloc[:, 1].nunique()}"
        )

        print(
            "\nColumns:"
        )

        for column in dataframe.columns:

            print(
                f"  - {column}"
            )


if __name__ == "__main__":

    loader = EDADataLoader()

    dataset = loader.load_all()

    loader.summary(
        dataset.bus,
        name="Bus Measurements",
    )

    loader.summary(
        dataset.line,
        name="Line Measurements",
    )