"""
Feature selection and fusion for the power-grid anomaly detection
pipeline.

This module combines the feature families generated by:

    statistical.py
    electrical.py
    frequency.py
    graph.py

and produces a clean ML-ready feature matrix.

Pipeline
--------
Engineered features
        |
        v
Metadata separation
        |
        v
Missing-value filtering
        |
        v
Constant / low-variance filtering
        |
        v
Correlation pruning
        |
        v
Final feature matrix
        |
        +--> Standardized ML matrix
        |
        +--> Optional PCA representation

Important
---------
This is an UNSUPERVISED anomaly-detection pipeline.

We therefore do not use anomaly labels for feature selection.

The selector can be fitted on training/normal data and subsequently
applied to validation/test data without refitting.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

import numpy as np
import pandas as pd
import joblib

from sklearn.decomposition import PCA
from sklearn.feature_selection import VarianceThreshold
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

from src.data.split_dataset import (
    TemporalSplitConfig,
    split_aligned_data,
)


                                                                        
               
                                                                        


@dataclass
class FeatureSelectionConfig:
    """
    Configuration for feature selection and fusion.
    """

                                                                    
                 
                                                                    

    max_missing_fraction: float = 0.40

                                                                    
              
                                                                    

    variance_threshold: float = 0.0

                                                                    
                 
                                                                    

    correlation_threshold: float = 0.95

                                                                    
             
                                                                    

    scale_features: bool = True

                                                                    
                
                                                                    

    imputation_strategy: str = "median"

                                                                    
         
                                                                    

    enable_pca: bool = False

    pca_variance: float = 0.95

                                                                    
              
                                                                    

    metadata_columns: tuple[str, ...] = (
        "timestamp",
        "bus_id",
        "line_id",
        "from_bus",
        "to_bus",
        "in_service",
    )


                                                                        
                  
                                                                        


class FeatureSelector:
    """
    Fit and apply an unsupervised feature-selection pipeline.
    """

    def __init__(
        self,
        config: FeatureSelectionConfig | None = None,
    ) -> None:

        self.config = (
            config
            if config is not None
            else FeatureSelectionConfig()
        )

        self.feature_columns_: list[str] = []

        self.initial_feature_columns_: list[str] = []

        self.removed_missing_: list[str] = []

        self.removed_variance_: list[str] = []

        self.removed_correlation_: list[str] = []

        self.imputer_: SimpleImputer | None = None

        self.scaler_: StandardScaler | None = None

        self.variance_selector_: VarianceThreshold | None = None

        self.pca_: PCA | None = None

        self.is_fitted_: bool = False

        self.selection_summary_: dict = {}

                                                                        
                      
                                                                        

        self.selected_features_ = None

        self.feature_means_ = None

        self.feature_variances_ = None

        self.feature_correlations_ = None

        self.is_fitted_ = False

                                                                        
                
                                                                        

    @staticmethod
    def _validate_dataframe(
        dataframe: pd.DataFrame,
    ) -> None:

        if not isinstance(
            dataframe,
            pd.DataFrame,
        ):

            raise TypeError(
                "Expected pandas DataFrame."
            )

        if dataframe.empty:

            raise ValueError(
                "Input dataframe is empty."
            )

                                                                        
                              
                                                                        

    def get_feature_columns(
        self,
        dataframe: pd.DataFrame,
    ) -> list[str]:
        """
        Return numeric ML feature columns.

        Metadata / identifiers are excluded.
        """

        self._validate_dataframe(
            dataframe
        )

        excluded = set(
            self.config.metadata_columns
        )

        numeric_columns = (
            dataframe
            .select_dtypes(
                include=[np.number]
            )
            .columns
            .tolist()
        )

        return [
            column
            for column in numeric_columns
            if column not in excluded
        ]

                                                                        
                             
                                                                        

    def _filter_missing(
        self,
        dataframe: pd.DataFrame,
        feature_columns: list[str],
    ) -> list[str]:
        """
        Remove features with excessive missing values.
        """

        missing_fraction = (
            dataframe[
                feature_columns
            ]
            .isna()
            .mean()
        )

        keep = (
            missing_fraction
            <= self.config.max_missing_fraction
        )

        removed = (
            missing_fraction[
                ~keep
            ]
            .index
            .tolist()
        )

        self.removed_missing_ = removed

        return (
            missing_fraction[
                keep
            ]
            .index
            .tolist()
        )

                                                                        
                         
                                                                        

    def _remove_correlated(
        self,
        dataframe: pd.DataFrame,
        feature_columns: list[str],
    ) -> list[str]:
        """
        Remove highly correlated redundant features.

        For each pair:

            |corr(x_i, x_j)| > threshold

        one feature is removed.

        We retain the feature appearing earlier in the dataframe.
        """

        if len(feature_columns) <= 1:

            self.removed_correlation_ = []

            return feature_columns

        correlation = (
            dataframe[
                feature_columns
            ]
            .corr(
                method="pearson"
            )
            .abs()
        )

        upper = (
            correlation.where(
                np.triu(
                    np.ones(
                        correlation.shape
                    ),
                    k=1,
                ).astype(bool)
            )
        )

        to_remove = [
            column
            for column in upper.columns
            if any(
                upper[column]
                > self.config.correlation_threshold
            )
        ]

        self.removed_correlation_ = (
            to_remove
        )

        return [
            column
            for column in feature_columns
            if column not in to_remove
        ]

                                                                        
         
                                                                        

              
               
                                  
                             
             
                                             

                    
                    
                    
                            

                   
                   
                                                                     
               
             

                                   
                       
           

                                                                          
                                      
                                                                          

                             
                                       
                           
               
           

                                 

                               
                                                     
               

                                           
                                    
           

                                                                          
                               
                                                                          

                             
                                   
                            
                                  
               
           

                                 

                               
                                                 
                                            
               

                                                                          
                                 
           
                                                        
                                                                          

                               
                            
                                                          
               
           

                                              
                        
                                 
               
           

                           
                
                                      
                                    
           

                                                                          
                               
                                                                          

                                     
                                
                                                          
               
           

                                      
               
           

                           
                                     
                            
           

                               
                     
                               
                     
                                  
                                
               
                     
           

                                    
                     
                                            
                                                 
           

                                   

                               
                                                 
                                       
               

                                                                          
                                  
                                                                          

                            
                                      
                    
                                       
                    
                                    
               
           

                                

                               
                                                 
                                          
               

                                   
                            
           

                                                                          
                              
                                                                          

                           
                            
                                                          
               
           

                            
                        
                                       
               
           

                                                                          
                       
                                                                          

                                        

                              
                                  
               

                           
                               
                             
                                
                                               
                       
                   
               

                               
                           
               

                                                                          
                         
                                                                          

                                    

                           
                               
                             
                                
                                               
                       
                   
               

                                          

                               
                                  
                                 
                                   
                       
                   

                              
                                
                                              
                   
               

                            
                           
               

                                                                          
                    
                                                                          

                                     
                                      
                                               
                

                                     
                                       
                

                                      
                                        
                

                                         
                                           
                

                                    
                                       
                

                              
                                        
                
           

                                   

                                      
                                  
                      
                                         
               

                                      
                                          
                        
                           
                                            
                        
               

                                

                     

    def fit(
        self,
        dataframe: pd.DataFrame,
    ) -> "FeatureSelector":
        """
        Fit feature-selection decisions using TRAINING data only.

        The learned feature-selection state is stored internally and
        can subsequently be applied to validation/test data using
        transform().
        """

        if not isinstance(
            dataframe,
            pd.DataFrame,
        ):
            raise TypeError(
                "Expected pandas DataFrame."
            )

        if dataframe.empty:
            raise ValueError(
                "Cannot fit feature selector "
                "on an empty dataframe."
            )

                                                                    
                         
                                                                    

        data = dataframe.copy()

                                                                    
                                  
                                                                    

        metadata_columns = [
            "timestamp",
            "bus_id",
            "line_id",
            "from_bus",
            "to_bus",
            "in_service",
        ]

        feature_columns = [
            column
            for column in data.columns
            if column not in metadata_columns
        ]

        if not feature_columns:
            raise ValueError(
                "No feature columns available."
            )

        data = data[
            feature_columns
        ]

                                                                    
                             
                                                                    

        data = data.apply(
            pd.to_numeric,
            errors="coerce",
        )

                                                                    
                                  
         
                    
                                                   
                                                                    

        missing_fraction = (
            data.isna()
            .mean()
        )

        missing_threshold = getattr(
            self,
            "missing_threshold",
            0.30,
        )

        valid_missing = (
            missing_fraction
            <= missing_threshold
        )

        missing_removed = (
            (~valid_missing)
            .sum()
        )

        data = data.loc[
            :,
            valid_missing
        ]

                                                                    
                             
                                                                    

        variance_threshold = getattr(
            self,
            "variance_threshold",
            1e-8,
        )

        variances = (
            data.var(
                numeric_only=True
            )
        )

        valid_variance = (
            variances
            > variance_threshold
        )

        variance_removed = (
            (~valid_variance)
            .sum()
        )

        data = data.loc[
            :,
            valid_variance
        ]

                                                                    
                                
         
                                                                
                                                                    

        correlation_threshold = getattr(
            self,
            "correlation_threshold",
            0.95,
        )

        correlation_removed = []

        if (
            len(data.columns)
            > 1
        ):

            correlation_matrix = (
                data.corr(
                    method="pearson"
                )
                .abs()
            )

            upper = (
                correlation_matrix
                .where(
                    np.triu(
                        np.ones(
                            correlation_matrix.shape,
                            dtype=bool,
                        ),
                        k=1,
                    )
                )
            )

            for column in upper.columns:

                if (
                    upper[column]
                    > correlation_threshold
                ).any():

                    correlation_removed.append(
                        column
                    )

        data = data.drop(
            columns=correlation_removed,
            errors="ignore",
        )

                                                                    
                             
                                                                    

        self.selected_features_ = (
            data.columns.tolist()
        )

        self.feature_means_ = (
            data.mean()
        )

        self.feature_variances_ = (
            variances
        )

        self.feature_correlations_ = (
            correlation_removed
        )

        self.is_fitted_ = True

                                                                    
                            
                                                                    

        self.selection_summary_ = {
            "initial_features": len(
                feature_columns
            ),
            "removed_missing": int(
                missing_removed
            ),
            "removed_variance": int(
                variance_removed
            ),
            "removed_correlation": int(
                correlation_removed.__len__()
            ),
            "final_features": len(
                self.selected_features_
            ),
        }

        return self

                                                                        
               
                                                                        

                    
               
                                  
                        
             
                                                      

                                                                   
             

                                 

                                 
                                                        
               

                                   
                       
           

                             
                                        
                                      
           

                             

                               
                                               
                                        
                                              
               

                                      
                        
                                       
               
           

                                      

                                         
                   
               

                                   

                                      
                   
               

                         
                              
                                 
                                
                   
               

               

                         
                                       
               

                              
                
                              
                                    
           

    def transform(
        self,
        dataframe: pd.DataFrame,
    ) -> pd.DataFrame:
        """
        Apply a previously fitted feature-selection state.

        No feature-selection statistics are recalculated.
        """

        if not self.is_fitted_:

            raise RuntimeError(
                "FeatureSelector has not been fitted. "
                "Call fit() on training data first."
            )

        data = dataframe.copy()

        metadata_columns = [
            "timestamp",
            "bus_id",
            "line_id",
            "from_bus",
            "to_bus",
            "in_service",
        ]

        feature_columns = [
            column
            for column in data.columns
            if column not in metadata_columns
        ]

        data = data[
            feature_columns
        ]

        data = data.apply(
            pd.to_numeric,
            errors="coerce",
        )

                                                                    
                                                        
                                                                    

        missing_features = [
            column
            for column in self.selected_features_
            if column not in data.columns
        ]

        if missing_features:

            raise ValueError(
                "Validation/test data is missing "
                "features selected during training: "
                f"{missing_features}"
            )

                                                                    
                                                          
                                                                    

        data = data[
            self.selected_features_
        ].copy()

                                                                    
                                                       
                                                                    

        data = data.fillna(
            self.feature_means_
        )

        return data

                                                                        
                   
                                                                        

    def fit_transform(
        self,
        dataframe: pd.DataFrame,
    ) -> pd.DataFrame:
        """
        Fit the selector and transform the same dataset.
        """

        self.fit(
            dataframe
        )

        return self.transform(
            dataframe
        )

                                                                        
                                
                                                                        

    def get_selected_features(
        self,
    ) -> list[str]:
        """
        Return selected feature names.
        """

        if not self.is_fitted_:

            raise RuntimeError(
                "FeatureSelector has not been fitted."
            )

        return self.feature_columns_.copy()

                                                                        
                                 
                                                                        

    def save_feature_list(
        self,
        path: str | Path,
    ) -> Path:
        """
        Save selected feature names as CSV.
        """

        if not self.is_fitted_:

            raise RuntimeError(
                "FeatureSelector has not been fitted."
            )

        path = Path(
            path
        )

        path.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        output = pd.DataFrame(
            {
                "feature": (
                    self.feature_columns_
                )
            }
        )

        output.to_csv(
            path,
            index=False,
        )

        return path

                                                                        
                  
                                                                        

    def save_summary(
        self,
        path: str | Path,
    ) -> Path:
        """
        Save feature-selection summary.
        """

        path = Path(
            path
        )

        path.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        summary = pd.DataFrame(
            [
                self.selection_summary_
            ]
        )

        summary.to_json(
            path,
            orient="records",
            indent=2,
        )

        return path


                                                                        
                                     
                                                                        


def merge_bus_features(
    statistical_path: str | Path,
    electrical_path: str | Path,
    frequency_path: str | Path,
    graph_path: str | Path,
) -> pd.DataFrame:
    """
    Merge all bus feature families.

    Merge keys:

        timestamp
        bus_id
    """

    statistical = pd.read_csv(
        statistical_path
    )

    electrical = pd.read_csv(
        electrical_path
    )

    frequency = pd.read_csv(
        frequency_path
    )

    graph = pd.read_csv(
        graph_path
    )

    merge_keys = [
        "timestamp",
        "bus_id",
    ]

    result = statistical.copy()

    for dataframe in [
        electrical,
        frequency,
        graph,
    ]:

        result = result.merge(
            dataframe,
            how="left",
            on=merge_keys,
            suffixes=(
                "",
                "_duplicate",
            ),
        )

        duplicate_columns = [
            column
            for column in result.columns
            if column.endswith(
                "_duplicate"
            )
        ]

        if duplicate_columns:

            result = result.drop(
                columns=duplicate_columns
            )

    return result


                                                                        
                                      
                                                                        


def merge_line_features(
    statistical_path: str | Path,
    electrical_path: str | Path,
    frequency_path: str | Path,
    graph_path: str | Path,
) -> pd.DataFrame:
    """
    Merge all line feature families.

    Merge keys:

        timestamp
        line_id
    """

    statistical = pd.read_csv(
        statistical_path
    )

    electrical = pd.read_csv(
        electrical_path
    )

    frequency = pd.read_csv(
        frequency_path
    )

    graph = pd.read_csv(
        graph_path
    )

    merge_keys = [
        "timestamp",
        "line_id",
    ]

    result = statistical.copy()

    for dataframe in [
        electrical,
        frequency,
        graph,
    ]:

        result = result.merge(
            dataframe,
            how="left",
            on=merge_keys,
            suffixes=(
                "",
                "_duplicate",
            ),
        )

        duplicate_columns = [
            column
            for column in result.columns
            if column.endswith(
                "_duplicate"
            )
        ]

        if duplicate_columns:

            result = result.drop(
                columns=duplicate_columns
            )

    return result

                                                                        
                     
                                                                        


def extract_metadata(
    dataframe: pd.DataFrame,
    entity_type: str,
) -> pd.DataFrame:
    """
    Extract temporal and entity-identification metadata from the
    original fused feature dataframe.

    Parameters
    ----------
    dataframe:
        Original fused dataframe BEFORE FeatureSelector.transform().

    entity_type:
        Either "bus" or "line".

    Returns
    -------
    DataFrame
        Metadata aligned row-by-row with the final feature matrix.
    """

    if entity_type not in {
        "bus",
        "line",
    }:

        raise ValueError(
            "entity_type must be either "
            "'bus' or 'line'."
        )

                                                                    
                     
                                                                    

    required = [
        "timestamp",
    ]

                                                                    
                              
                                                                    

    if entity_type == "bus":

        required.append(
            "bus_id"
        )

    else:

        required.append(
            "line_id"
        )

                                                                    
                                                          
        optional = [
            "from_bus",
            "to_bus",
            "in_service",
            "edge_in_operational_graph",
        ]

        for column in optional:

            if column in dataframe.columns:

                required.append(
                    column
                )

                                                                    
               
                                                                    

    missing = (
        set(required)
        - set(dataframe.columns)
    )

    if missing:

        raise ValueError(
            f"Cannot extract {entity_type} metadata. "
            f"Missing columns: {sorted(missing)}"
        )

                                                                    
                                  
                                                                    

    metadata = dataframe[
        required
    ].copy()

                                                                    
                          
                                                                    

    metadata[
        "timestamp"
    ] = pd.to_datetime(
        metadata[
            "timestamp"
        ],
        errors="coerce",
    )

    if metadata[
        "timestamp"
    ].isna().any():

        raise ValueError(
            f"{entity_type} metadata contains invalid "
            "timestamps."
        )

                                                                    
                                  
                                                                    

    entity_column = (
        "bus_id"
        if entity_type == "bus"
        else "line_id"
    )

    metadata[
        entity_column
    ] = pd.to_numeric(
        metadata[
            entity_column
        ],
        errors="coerce",
    )

    if metadata[
        entity_column
    ].isna().any():

        raise ValueError(
            f"{entity_type} metadata contains invalid "
            f"{entity_column} values."
        )

    metadata[
        entity_column
    ] = metadata[
        entity_column
    ].astype(int)

    return metadata.reset_index(
        drop=True
    )


                                                                        
      
                                                                        


if __name__ == "__main__":

    print()
    print(
        "=" * 70
    )

    print(
        "FEATURE SELECTION AND FUSION"
    )

    print(
        "=" * 70
    )

                                                                    
           
                                                                    

    bus_statistical_path = (
        "data/features/bus/"
        "statistical_features.csv"
    )

    bus_electrical_path = (
        "data/features/bus/"
        "electrical_features.csv"
    )

    bus_frequency_path = (
        "data/features/bus/"
        "frequency_features.csv"
    )

    bus_graph_path = (
        "data/features/bus/"
        "graph_features.csv"
    )

    line_statistical_path = (
        "data/features/line/"
        "statistical_features.csv"
    )

    line_electrical_path = (
        "data/features/line/"
        "electrical_features.csv"
    )

    line_frequency_path = (
        "data/features/line/"
        "frequency_features.csv"
    )

    line_graph_path = (
        "data/features/line/"
        "graph_features.csv"
    )

                                                                    
                        
                                                                    

    print(
        "\nMerging bus feature families..."
    )

    bus_data = merge_bus_features(
        bus_statistical_path,
        bus_electrical_path,
        bus_frequency_path,
        bus_graph_path,
    )

    print(
        f"Raw bus feature matrix:"
        f" {bus_data.shape}"
    )

                                                                    
                         
                                                                    

    print(
        "\nMerging line feature families..."
    )

    line_data = merge_line_features(
        line_statistical_path,
        line_electrical_path,
        line_frequency_path,
        line_graph_path,
    )

    print(
        f"Raw line feature matrix:"
        f" {line_data.shape}"
    )

                                                                    
                        
                                                                    

    config = FeatureSelectionConfig(
        max_missing_fraction=0.40,
        variance_threshold=0.0,
        correlation_threshold=0.95,
        scale_features=True,
        imputation_strategy="median",
        enable_pca=False,
    )

                                                                        
                        
                                                                        

    print()
    print(
        "-" * 70
    )

    print(
        "BUS TEMPORAL SPLIT"
    )

    print(
        "-" * 70
    )

    bus_metadata = extract_metadata(
        bus_data,
        entity_type="bus",
    )

    bus_features_raw = (
        bus_data.drop(
            columns=[
                "timestamp",
                "bus_id",
            ],
            errors="ignore",
        )
    )

                                                                    
                                                             
                                                                    

    bus_splits = split_aligned_data(
        features=bus_features_raw,
        metadata=bus_metadata,
        config=TemporalSplitConfig(
            train_fraction=0.60,
            validation_fraction=0.20,
            test_fraction=0.20,
        ),
    )

    bus_train_raw, bus_train_metadata = (
        bus_splits["train"]
    )

    bus_val_raw, bus_val_metadata = (
        bus_splits["validation"]
    )

    bus_test_raw, bus_test_metadata = (
        bus_splits["test"]
    )

    print(
        "Train:",
        bus_train_raw.shape,
    )

    print(
        "Validation:",
        bus_val_raw.shape,
    )

    print(
        "Test:",
        bus_test_raw.shape,
    )

                                                                        
                           
                                                                        

    print()
    print(
        "-" * 70
    )

    print(
        "BUS FEATURE SELECTION"
    )

    print(
        "-" * 70
    )

    bus_selector = FeatureSelector(
        config=config
    )

                                                                    
                                
                                                                    

    bus_selector.fit(
        bus_train_raw
    )

                                                                    
                                     
                                                                    

    bus_train = (
        bus_selector.transform(
            bus_train_raw
        )
    )

    bus_validation = (
        bus_selector.transform(
            bus_val_raw
        )
    )

    bus_test = (
        bus_selector.transform(
            bus_test_raw
        )
    )

    print(
        "Selected bus features:",
        len(
            bus_selector.selected_features_
        ),
    )

    print(
        "Bus train matrix:",
        bus_train.shape,
    )

    print(
        "Bus validation matrix:",
        bus_validation.shape,
    )

    print(
        "Bus test matrix:",
        bus_test.shape,
    )

                                                                        
                                        
                                                                        

    final_dir = Path(
        "data/features/final"
    )

    final_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    bus_train.to_csv(
        final_dir
        / "bus_train_features.csv",
        index=False,
    )

    bus_validation.to_csv(
        final_dir
        / "bus_validation_features.csv",
        index=False,
    )

    bus_test.to_csv(
        final_dir
        / "bus_test_features.csv",
        index=False,
    )

    bus_train_metadata.to_csv(
        final_dir
        / "bus_train_metadata.csv",
        index=False,
    )

    bus_val_metadata.to_csv(
        final_dir
        / "bus_validation_metadata.csv",
        index=False,
    )

    bus_test_metadata.to_csv(
        final_dir
        / "bus_test_metadata.csv",
        index=False,
    )

    joblib.dump(
        bus_selector,
        "models/bus_feature_selector.joblib",
    )

                                                                        
                         
                                                                        

    print()
    print(
        "-" * 70
    )

    print(
        "LINE TEMPORAL SPLIT"
    )

    print(
        "-" * 70
    )

    line_metadata = extract_metadata(
        line_data,
        entity_type="line",
    )

    line_features_raw = (
        line_data.drop(
            columns=[
                "timestamp",
                "line_id",
                "from_bus",
                "to_bus",
                "in_service",
            ],
            errors="ignore",
        )
    )

    line_splits = split_aligned_data(
        features=line_features_raw,
        metadata=line_metadata,
        config=TemporalSplitConfig(
            train_fraction=0.60,
            validation_fraction=0.20,
            test_fraction=0.20,
        ),
    )

    line_train_raw, line_train_metadata = (
        line_splits["train"]
    )

    line_val_raw, line_val_metadata = (
        line_splits["validation"]
    )

    line_test_raw, line_test_metadata = (
        line_splits["test"]
    )

    print(
        "Train:",
        line_train_raw.shape,
    )

    print(
        "Validation:",
        line_val_raw.shape,
    )

    print(
        "Test:",
        line_test_raw.shape,
    )

                                                                        
                            
                                                                        

    print()
    print(
        "-" * 70
    )

    print(
        "LINE FEATURE SELECTION"
    )

    print(
        "-" * 70
    )

    line_selector = FeatureSelector(
        config=config
    )

                                                                    
                                
                                                                    

    line_selector.fit(
        line_train_raw
    )

                                                                    
                               
                                                                    

    line_train = (
        line_selector.transform(
            line_train_raw
        )
    )

    line_validation = (
        line_selector.transform(
            line_val_raw
        )
    )

    line_test = (
        line_selector.transform(
            line_test_raw
        )
    )

    print(
        "Selected line features:",
        len(
            line_selector.selected_features_
        ),
    )

    print(
        "Line train matrix:",
        line_train.shape,
    )

    print(
        "Line validation matrix:",
        line_validation.shape,
    )

    print(
        "Line test matrix:",
        line_test.shape,
    )

                                                                        
                                         
                                                                        

    line_train.to_csv(
        final_dir
        / "line_train_features.csv",
        index=False,
    )

    line_validation.to_csv(
        final_dir
        / "line_validation_features.csv",
        index=False,
    )

    line_test.to_csv(
        final_dir
        / "line_test_features.csv",
        index=False,
    )

    line_train_metadata.to_csv(
        final_dir
        / "line_train_metadata.csv",
        index=False,
    )

    line_val_metadata.to_csv(
        final_dir
        / "line_validation_metadata.csv",
        index=False,
    )

    line_test_metadata.to_csv(
        final_dir
        / "line_test_metadata.csv",
        index=False,
    )

    joblib.dump(
        line_selector,
        "models/line_feature_selector.joblib",
    )